import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      label: "Introduction",
      id: 'intro'
    },
    {
      type: 'doc',
      label: "Quickstart",
      id: 'Quickstart'
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        {
          type: 'doc',
          label: "PiPy Installation",
          id: 'Installation/PiPy'
        },
        {
          type: 'doc',
          label: "Docker Installation",
          id: 'Installation/Docker'
        },
        {
          type: 'doc',
          label: "Windows Installation",
          id: 'Installation/Windows'
        }
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        {
          type: 'doc',
          label: "Celery Configuration",
          id: 'Configuration/Celery'
        },
        {
          type: 'doc',
          label: "Chromium Configuration",
          id: 'Configuration/Chromium'
        },
        {
          type: 'doc',
          label: "Alerts and Reports",
          id: 'Configuration/AlertsAndReports'
        }

      ]
    },
    {
      type: 'category',
      label: 'Customization',
      items: [
        {
          type: 'doc',
          label: "Superset Customization",
          id: 'Customization/CustomizingSuperset'
        }
      ],

    },
    {
      type: 'category',
      label: 'Embedding',
      items: [
        {
          type: 'category',
          label: 'Secure Embedding',
          items: [
            {
              type: 'doc',
              label: "Embedding Setup",
              id: 'Embedding/EmbeddingSetup'
            },
            {
              type: 'doc',
              label: "Embedding In Angular",
              id: 'Embedding/applications/AngularEmbedding'
            },
            {
              type: 'doc',
              label: "Embedding In React",
              id: 'Embedding/applications/ReactEmbedding'
            },
            {
              type: 'doc',
              label: "Embedding In Django",
              id: 'Embedding/applications/DjangoEmbedding'
            },
            {
              type: 'doc',
              label: "Embedding In Javascript",
              id: 'Embedding/applications/PlainJsEmbedding'
            },            
          ]
        },

        {
          type: 'doc',
          label: "Public Dashboard embedding",
          id: 'Embedding/EmbeddingPublicReport'
        }
      ],

    },
    {
      type: 'category',
      label: 'Customizing Visuals',
      items: [
        {
          type: 'doc',
          label: "Customizing Table",
          id: 'Visuals/BeautifyingTables'
        }
      ],

    },
  ],

};

export default sidebars;
